// output/Button.vue
<script>

export default {
	name: 'Button',
	props: {
		href: {
			type: String,
			default: null
		},
		target: {
			type: String,
			default: null
		},
		style: {
			type: Object,
			default: () => ({})
		},
		onClick: {
			type: Function,
			default: null
		}
	},
	methods: {
		handleClick(event) {
			if (this.onClick) {
				this.onClick(event);
			}
		}
	}
};
</script>

<template>
	<div>
		<a v-if="href" :class="'Button'" :href="href" :target="target" :style="style" @click="handleClick">
			<slot />
		</a>
		<button v-else :class="'Button'" :style="style" @click="handleClick">
			<slot />
		</button>
	</div>
</template>

<style scoped>
.Button {
	display: block;
	border-radius: 5px;
	border: 1px solid var(--figma-color-border);
	padding: 0 7px;
	line-height: 22px;
	text-decoration: none;
	color: var(--figma-color-text);
}
</style>

// test-files/Button.svelte
<script lang="ts">
	interface Props {
		children: () => any;
		href?: string;
		target?: string;
		style?: string;
		onclick?: () => void;
	}

	let { children, href, target, style, onclick }: Props = $props();
</script>

{#if href}
	<a class="Button" {href} {target} {style} {onclick}>{@render children()}</a>
{:else}
	<button class="Button" {style} {onclick}>
		{@render children()}
	</button>
{/if}

<style>
	.Button {
		display: block;
		border-radius: 5px;
		border: 1px solid var(--figma-color-border);
		padding: 0 7px;
		line-height: 22px;
		text-decoration: none;
		color: var(--figma-color-text);
	}
</style>
