// output/Button.svelte
<script>let { children, href, target, style, onclick } = $props();
</script>

{#if href}
  <a class="Button" {href} {target} {style} {onclick}>{@render children()}</a>
{:else}
  <button class="Button" {style} {onclick}>
    {@render children()}
  </button>
{/if}

<style>
  .Button {
    display: block;
    border-radius: 5px;
    border: 1px solid var(--figma-color-border);
    padding: 0 7px;
    line-height: 22px;
    text-decoration: none;
    color: var(--figma-color-text);
  }
</style>

// output/Button.jsx
import React from "react";

const Button = ({ children, href, target, style, onClick }) => {
  const buttonStyle = {
    display: "block",
    borderRadius: "5px",
    border: "1px solid var(--figma-color-border)",
    padding: "0 7px",
    lineHeight: "22px",
    textDecoration: "none",
    color: "var(--figma-color-text)",
    ...style // Merge with any passed styles
  };

  if (href) {
    return (
      <a href={href} target={target} style={buttonStyle} onClick={onClick}>
        {children}
      </a>);

  }

  return (
    <button style={buttonStyle} onClick={onClick}>
      {children}
    </button>);

};

export default Button;
